In [2]:
import numpy as np
import pandas as pd
import matplotlib
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

y_train = pd.read_csv('y_train_use2.csv', index_col = 0)
x_train = pd.read_csv('x_filter.csv', index_col = 0)

In [4]:
inner_numbers_list = [
    "99", "109", "119", "129", "139", "149", "159", "169", "179", "189", "199",
    "109", "120", "131", "142", "153", "164", "175", "186", "197", "208", "219",
    "119", "131", "143", "155", "167", "179", "191", "203", "215", "227", "239",
    "129", "142", "155", "168", "181", "194", "207", "220", "233", "246", "259",
    "139", "153", "167", "181", "195", "209", "223", "237", "251", "265", "279",
    "149", "164", "179", "194", "209", "224", "239", "254", "269", "284", "299",
    "159", "175", "191", "207", "223", "239", "255", "271", "287", "303", "319",
    "169", "186", "203", "220", "237", "254", "271", "288", "305", "322", "339",
    "179", "197", "215", "233", "251", "269", "287", "305", "323", "341", "359",
    "189", "208", "227", "246", "265", "284", "303", "322", "341", "360", "379"
]

# Assuming you have a DataFrame called df with columns numbers 0 to 783
# You can create a new DataFrame with only the referenced columns like this:
referenced_columns = [int(num) for num in inner_numbers_list]  # Convert strings to integers
x_train_hopefully = x_train.iloc[:, referenced_columns]

In [5]:
x_train_hopefully.shape

(64001, 110)

In [6]:
np.random.seed( 28 )

X_train_samp, X_test_samp, y_train_samp, y_test_samp = train_test_split( x_train_hopefully, y_train, test_size=0.75 )

In [7]:
X_train_samp

,99,109,119,129,139,149,159,169,179,189,...,208,227,246,265,284,303,322,341,360,379
13020,130,110,128,65,107,43,40,86,32,56,...,39,62,77,87,19,117,168,73,132,197
41856,141,28,95,100,1,136,113,117,144,127,...,144,163,136,132,163,142,104,148,143,100
11727,151,97,126,100,80,87,114,174,126,139,...,163,188,141,189,148,156,194,123,172,188
73633,108,147,108,81,149,82,69,203,92,93,...,137,188,121,176,131,165,185,73,157,157
78253,83,51,67,57,3,36,65,114,66,141,...,152,152,134,180,131,46,117,111,1,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67775,140,102,96,70,118,83,67,138,71,70,...,82,143,91,136,150,134,174,129,159,184
76901,167,176,153,85,142,88,71,172,94,123,...,139,185,163,164,188,192,209,193,189,215
32075,102,0,17,47,0,52,24,85,97,51,...,120,150,121,119,147,141,117,112,167,91
4980,121,110,109,73,98,71,65,100,70,89,...,80,113,106,118,115,125,131,128,126,135
51758,105,37,94,60,26,52,87,114,73,121,...,106,146,137,142,150,129,151,124,109,151

In [8]:
dT = DecisionTreeClassifier()
dT.fit( X_train_samp, y_train_samp )
predTrain_dT = dT.predict( X_train_samp )

In [10]:
import sklearn.metrics
from sklearn.tree import plot_tree
from sklearn.ensemble import RandomForestClassifier

print( sklearn.metrics.classification_report( y_train_samp, predTrain_dT ) )

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       724
           1       1.00      1.00      1.00       180
           2       1.00      1.00      1.00       718
           3       1.00      1.00      1.00      1663
           4       1.00      1.00      1.00       369
           5       1.00      1.00      1.00       473
           6       1.00      1.00      1.00        56
           7       1.00      1.00      1.00       402
           8       1.00      1.00      1.00       247
           9       1.00      1.00      1.00       118
          10       1.00      1.00      1.00       167
          11       1.00      1.00      1.00       125
          12       1.00      1.00      1.00       194
          13       1.00      1.00      1.00        23
          14       1.00      1.00      1.00     10541

    accuracy                           1.00     16000
   macro avg       1.00      1.00      1.00     16000
weighted avg       1.00      1.00      1.00     16000